<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="dmodule">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ident">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="dmc" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="title" type="xs:string"/>
        <xs:element name="applic" minOccurs="0" type="xs:string"/>
        <xs:element name="content">
          <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
              <xs:element name="para">
                <xs:complexType mixed="true">
                  <xs:attribute name="id" type="xs:string"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="ref">
                <xs:complexType>
                  <xs:attribute name="target" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="graphic">
                <xs:complexType>
                  <xs:attribute name="icn" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="table">
                <xs:complexType>
                  <xs:sequence>
                    <xs:any minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:choice>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>
  </xs:element>
</xs:schema>
